=== josue-ponte/laboratorio5/src/resources/universityCardList.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.example.org/Product"
           xmlns:tns="http://www.example.org/Product">

    <xs:element name="universityCardList">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="universityCard" type="tns:universityCard" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="universityCard">
        <xs:sequence>
            <xs:element name="university"		type="xs:string"/>
            <xs:element name="code"			    type="xs:string"/>
            <xs:element name="dni"				type="xs:string"/>
            <xs:element name="lastName"		    type="xs:string"/>
            <xs:element name="firstName"		type="xs:string"/>
            <xs:element name="faculty"			type="xs:string"/>
            <xs:element name="career"			type="xs:string"/>
            <xs:element name="year"				type="xs:integer"/>
            <xs:element name="incomeYear"		type="xs:string"/>
            <xs:element name="expirationDate"	type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== josue-ponte/laboratorio5/out/production/Laboratorio5/resources/universityCardList.xml
<?xml version="1.0" encoding="UTF-8"?>
<universityCardList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:noNamespaceSchemaLocation="universityCardList.xsd">
    <universityCard>
        <university>UNIVERSIDAD NACIONAL MAYOR DE SAN MARCOS</university>
        <code>15200134</code>
        <dni>76517361</dni>
        <lastName>CUADROS RAMOS</lastName>
        <firstName>KENT JHUNIOR</firstName>
        <faculty>INGENIERÍA DE SISTEMAS E INFORMÁTICA</faculty>
        <career>INGENIERIA DE SOFTWARE</career>
        <year>2021</year>
        <incomeYear>2021-2</incomeYear>
        <expirationDate>23-12-2022</expirationDate>
    </universityCard>
    <universityCard>
        <university>UNIVERSIDAD NACIONAL MAYOR DE SAN MARCOS</university>
        <code>17200133</code>
        <dni>76517368</dni>
        <lastName>ARMAS ABT</lastName>
        <firstName>MIGUEL RODRIGO</firstName>
        <faculty>INGENIERÍA DE SISTEMAS E INFORMÁTICA</faculty>
        <career>INGENIERIA DE SISTEMAS</career>
        <year>2021</year>
        <incomeYear>2021-2</incomeYear>
        <expirationDate>23-12-2022</expirationDate>
    </universityCard>
    <universityCard>
        <university>UNIVERSIDAD NACIONAL MAYOR DE SAN MARCOS</university>
        <code>17200134</code>
        <dni>76517369</dni>
        <lastName>BOADA CAJO</lastName>
        <firstName>EDINSON PAOLO</firstName>
        <faculty>INGENIERÍA DE SISTEMAS E INFORMÁTICA</faculty>
        <career>INGENIERIA DE SISTEMAS</career>
        <year>2021</year>
        <incomeYear>2021-2</incomeYear>
        <expirationDate>23-12-2022</expirationDate>
    </universityCard>
    <universityCard>
        <university>UNIVERSIDAD NACIONAL MAYOR DE SAN MARCOS</university>
        <code>15200134</code>
        <dni>76517361</dni>
        <lastName>CUADROS RAMOS</lastName>
        <firstName>KENT JHUNIOR</firstName>
        <faculty>INGENIERÍA DE SISTEMAS E INFORMÁTICA</faculty>
        <career>INGENIERIA DE SISTEMAS</career>
        <year>2021</year>
        <incomeYear>2021-2</incomeYear>
        <expirationDate>23-12-2022</expirationDate>
    </universityCard>
</universityCardList>
